name: Generate Datas

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: Augustorf01
          output: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
